
from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *
screen='login'
import sys
class Ui_SignIn(object):
    def setupUi(self, SignIn):
        print('hi')
        SignIn.setObjectName("SignIn")
        SignIn.resize(300, 533)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        SignIn.setFont(font)
        SignIn.setStyleSheet("background-color:#FFFFFF;")
        self.centralwidget = QWidget(SignIn)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(65, 206.5, 170, 120))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.username.setFont(font)
        self.username.setStyleSheet("border-radius:15px;border: 1px solid rgb(0, 0, 0);padding-top:4%;padding-bottom:4%;")
        self.username.setFrame(True)
        self.username.setCursorPosition(0)
        self.username.setAlignment(QtCore.Qt.AlignCenter)
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius:15px;\n"
"border: 1px solid rgb(0, 0, 0);\n"
"padding-top:4%;\n"
"padding-bottom:4%;")
        self.password.setFrame(True)
        self.password.setEchoMode(QLineEdit.Password)
        self.password.setCursorPosition(0)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SignInButton = QPushButton(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SignInButton.sizePolicy().hasHeightForWidth())
        self.SignInButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.SignInButton.setFont(font)
        self.SignInButton.setStyleSheet("border-radius:15px;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235); padding-top:6%;padding-bottom:6%;\n"
"padding-left:5%;\n"
"padding-right:5%")
        self.SignInButton.setObjectName("SignInButton")
        self.horizontalLayout.addWidget(self.SignInButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        SignIn.setCentralWidget(self.centralwidget)
        self.retranslateUi(SignIn)
        QtCore.QMetaObject.connectSlotsByName(SignIn)
        self.SignInButton.clicked.connect(self.signInFn)
    def retranslateUi(self, SignIn):
        _translate = QtCore.QCoreApplication.translate
        SignIn.setWindowTitle(_translate("SignIn", "MainWindow"))
        self.label.setText(_translate("SignIn", "Sign In"))
        self.username.setPlaceholderText(_translate("SignIn", "Username"))
        self.password.setPlaceholderText(_translate("SignIn", "Password"))
        self.SignInButton.setText(_translate("SignIn", "Sign In"))

    def signInFn(self):
        openHome()
        SignIn.hide()
        
        screen='home'

class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(300, 533)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HomePage.sizePolicy().hasHeightForWidth())
        HomePage.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(HomePage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 140, 300, 340))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.medicineSchedule = QPushButton(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medicineSchedule.sizePolicy().hasHeightForWidth())
        self.medicineSchedule.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.medicineSchedule.setFont(font)
        self.medicineSchedule.setStyleSheet("border-radius:15px ;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.medicineSchedule.setObjectName("medicineSchedule")
        self.horizontalLayout.addWidget(self.medicineSchedule)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:15px ;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:15px ;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_3 = QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius:15px ;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        HomePage.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "MainWindow"))
        self.label.setText(_translate("HomePage", "Welcome!"))
        self.medicineSchedule.setText(_translate("HomePage", "Medicine Schedule"))
        self.pushButton.setText(_translate("HomePage", "Status Update"))
        self.pushButton_2.setText(_translate("HomePage", "Checklist"))
        self.pushButton_3.setText(_translate("HomePage", "Contacts"))


class Ui_Contacts(object):
    def setupUi(self, Contacts):
        Contacts.setObjectName("Contacts")
        Contacts.resize(300, 533)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        Contacts.setFont(font)
        Contacts.setStyleSheet("background-color:#FFFFFF;\n"
"")
        self.centralwidget = QWidget(Contacts)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 220, 30))
        self.label.setStyleSheet("font-family:verdana;font-size:15pt;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.toolButton = QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(60, 90, 161, 31))
        self.toolButton.setStyleSheet("border-radius:15px ;border:1px solid rgb(135,206,235); background-color:rgb(135,206,235);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.toolButton.setObjectName("toolButton")
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 301, 280, 113))
        self.widget_2.setStyleSheet("background-color:rgb(202, 202, 202);border-radius:15px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_4 = QWidget(self.widget_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 0, 141, 118))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.name_2 = QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.name_2.setFont(font)
        self.name_2.setObjectName("name_2")
        self.verticalLayout_4.addWidget(self.name_2)
        self.relationship1_2 = QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relationship1_2.setFont(font)
        self.relationship1_2.setObjectName("relationship1_2")
        self.verticalLayout_4.addWidget(self.relationship1_2)
        self.number1_2 = QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.number1_2.setFont(font)
        self.number1_2.setObjectName("number1_2")
        self.verticalLayout_4.addWidget(self.number1_2)
        self.verticalLayoutWidget_5 = QWidget(self.widget_2)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(160, 10, 111, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_3 = QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_3.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QPushButton(self.verticalLayoutWidget_5)
        self.pushButton_4.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_5.addWidget(self.pushButton_4)
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 183, 280, 112))
        self.widget_3.setStyleSheet("background-color:rgb(202, 202, 202);border-radius:15px;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayoutWidget_6 = QWidget(self.widget_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 0, 141, 145))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.name_3 = QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.name_3.setFont(font)
        self.name_3.setObjectName("name_3")
        self.verticalLayout_6.addWidget(self.name_3)
        self.relationship1_3 = QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relationship1_3.setFont(font)
        self.relationship1_3.setObjectName("relationship1_3")
        self.verticalLayout_6.addWidget(self.relationship1_3)
        self.number1_3 = QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.number1_3.setFont(font)
        self.number1_3.setObjectName("number1_3")
        self.verticalLayout_6.addWidget(self.number1_3)
        self.verticalLayoutWidget_7 = QWidget(self.widget_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(160, 10, 111, 80))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_5 = QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_5.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_6 = QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_6.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.widget = QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 420, 280, 112))
        self.widget.setStyleSheet("background-color:rgb(202, 202, 202);border-radius:15px;")
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_2 = QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 141, 118))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_1 = QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.name_1.setFont(font)
        self.name_1.setObjectName("name_1")
        self.verticalLayout_2.addWidget(self.name_1)
        self.relationship1 = QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.relationship1.setFont(font)
        self.relationship1.setObjectName("relationship1")
        self.verticalLayout_2.addWidget(self.relationship1)
        self.number1 = QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.number1.setFont(font)
        self.number1.setObjectName("number1")
        self.verticalLayout_2.addWidget(self.number1)
        self.verticalLayoutWidget_3 = QWidget(self.widget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 10, 111, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QPushButton(self.verticalLayoutWidget_3)
        self.pushButton.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setStyleSheet("background-color:rgb(170, 255, 255);border-radius:15px;padding-top:2%;padding-bottom:2%;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        Contacts.setCentralWidget(self.centralwidget)

        self.retranslateUi(Contacts)
        QtCore.QMetaObject.connectSlotsByName(Contacts)

    def retranslateUi(self, Contacts):
        _translate = QtCore.QCoreApplication.translate
        Contacts.setWindowTitle(_translate("Contacts", "MainWindow"))
        self.label.setText(_translate("Contacts", "Important Contacts"))
        self.toolButton.setText(_translate("Contacts", "Add New"))
        self.name_2.setText(_translate("Contacts", "Name"))
        self.relationship1_2.setText(_translate("Contacts", "Relationship"))
        self.number1_2.setText(_translate("Contacts", "Number"))
        self.pushButton_3.setText(_translate("Contacts", "Call"))
        self.pushButton_4.setText(_translate("Contacts", "Message"))
        self.name_3.setText(_translate("Contacts", "Name"))
        self.relationship1_3.setText(_translate("Contacts", "Relationship"))
        self.number1_3.setText(_translate("Contacts", "Number"))
        self.pushButton_5.setText(_translate("Contacts", "Call"))
        self.pushButton_6.setText(_translate("Contacts", "Message"))
        self.name_1.setText(_translate("Contacts", "Name"))
        self.relationship1.setText(_translate("Contacts", "Relationship"))
        self.number1.setText(_translate("Contacts", "Number"))
        self.pushButton.setText(_translate("Contacts", "Call"))
        self.pushButton_2.setText(_translate("Contacts", "Message"))

class Ui_Checklist(object):
    def setupUi(self, Checklist):
        Checklist.setObjectName("Checklist")
        Checklist.resize(300, 533)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        Checklist.setFont(font)
        Checklist.setStyleSheet("background-color:#FFFFFF;\n"
"")
        self.centralwidget = QWidget(Checklist)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 220, 30))
        self.label.setStyleSheet("font-family:verdana;font-size:15pt;font-color:rgb(0, 0, 0)")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 110, 311, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_2 = QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QCheckBox(self.verticalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QCheckBox(self.verticalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox = QCheckBox(self.verticalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        Checklist.setCentralWidget(self.centralwidget)

        self.retranslateUi(Checklist)
        QtCore.QMetaObject.connectSlotsByName(Checklist)

    def retranslateUi(self, Checklist):
        _translate = QtCore.QCoreApplication.translate
        Checklist.setWindowTitle(_translate("Checklist", "MainWindow"))
        self.label.setText(_translate("Checklist", "Daily Checklist"))
        self.checkBox_2.setText(_translate("Checklist", "Attend the community function"))
        self.checkBox_3.setText(_translate("Checklist", "Have a full 3 meals"))
        self.checkBox_4.setText(_translate("Checklist", "Take a walk or get some excersise for 20 minutes"))
        self.checkBox.setText(_translate("Checklist", "Ask the drivers to get groceries"))
    

class Ui_StatusCheck(object):
    def setupUi(self, StatusCheck):
        StatusCheck.setObjectName("StatusCheck")
        StatusCheck.resize(300, 533)
        self.centralwidget = QWidget(StatusCheck)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 260, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 301, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:15px ;border:1px solid rgb(132, 235, 139); background-color:rgb(132, 235, 139);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QPushButton(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:15px ;border:1px solid rgb(235, 128, 139); background-color:rgb(235, 128, 139);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        StatusCheck.setCentralWidget(self.centralwidget)

        self.retranslateUi(StatusCheck)
        QtCore.QMetaObject.connectSlotsByName(StatusCheck)

    def retranslateUi(self, StatusCheck):
        _translate = QtCore.QCoreApplication.translate
        StatusCheck.setWindowTitle(_translate("StatusCheck", "MainWindow"))
        self.label.setText(_translate("StatusCheck", "Send a Status Update"))
        self.pushButton.setText(_translate("StatusCheck", "All Fine"))
        self.pushButton_2.setText(_translate("StatusCheck", "Help Required"))

    
    
"""if screen=='login':
    app = QApplication(sys.argv)
    SignIn = QMainWindow()
    ui = Ui_SignIn()
    ui.setupUi(SignIn)
    SignIn.show()
    print('hi')
    sys.exit(app.exec_())
    

else:
    app = QApplication(sys.argv)
    HomePage = QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()"""




def showSignIn():
    app = QApplication(sys.argv)
    SignIn = QMainWindow()
    ui = Ui_SignIn()
    ui.setupUi(SignIn)
    SignIn.show()
    sys.exit(app.exec_())


def openHome():
    app = QApplication(sys.argv)
    HomePage = QMainWindow()
    ui = Ui_HomePage()
    ui.setupUi(HomePage)
    HomePage.show()
    print('hello')
    sys.exit(app.exec_())

def openContact():
    app = QApplication(sys.argv)
    Contacts = QMainWindow()
    ui = Ui_Contacts()
    ui.setupUi(Contacts)
    Contacts.show()
    sys.exit(app.exec_())

def openStatus():
    app = QApplication(sys.argv)
    StatusCheck = QMainWindow()
    ui = Ui_StatusCheck()
    ui.setupUi(StatusCheck)
    StatusCheck.show()
    sys.exit(app.exec_())

def openChecklist():

    app = QApplication(sys.argv)
    Checklist = QMainWindow()
    ui = Ui_Checklist()
    ui.setupUi(Checklist)
    Checklist.show()
    sys.exit(app.exec_())

screen=int(input("which screen? "))
if screen==1:
    showSignIn()
elif screen==2:
    openHome()
elif screen==3:
    openContact()
elif screen==4:
    openStatus()
elif screen==5:
    openChecklist()
