# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Aksh\Downloads\status.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatusCheck(object):
    def setupUi(self, StatusCheck):
        StatusCheck.setObjectName("StatusCheck")
        StatusCheck.resize(300, 533)
        self.centralwidget = QtWidgets.QWidget(StatusCheck)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 260, 30))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 301, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:15px ;border:1px solid rgb(132, 235, 139); background-color:rgb(132, 235, 139);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-radius:15px ;border:1px solid rgb(235, 128, 139); background-color:rgb(235, 128, 139);padding-top:6%;padding-bottom:6%;padding-left:6%;padding-right:6%;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        StatusCheck.setCentralWidget(self.centralwidget)

        self.retranslateUi(StatusCheck)
        QtCore.QMetaObject.connectSlotsByName(StatusCheck)

    def retranslateUi(self, StatusCheck):
        _translate = QtCore.QCoreApplication.translate
        StatusCheck.setWindowTitle(_translate("StatusCheck", "MainWindow"))
        self.label.setText(_translate("StatusCheck", "Send a Status Update"))
        self.pushButton.setText(_translate("StatusCheck", "All Fine"))
        self.pushButton_2.setText(_translate("StatusCheck", "Help Required"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignIn = QtWidgets.QMainWindow()
    ui = Ui_SignIn()
    ui.setupUi(SignIn)
    SignIn.show()
    sys.exit(app.exec_())
